version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/guestbook
    env_file:
      - .env
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./backups:/backups
    restart: unless-stopped

volumes:
  mongodb_data:
  uploads:
